#### Работу выполнили:
#### Москаленко Ярослав Александрович
#### Кануков Денис Михайлович
#### Фетисов Данила Андреевич

#### Импортируем необходимые библиотеки

In [402]:
import numpy as np
import pandas as pd
import plotly.express as px

#### Импортируем таблицу с данными

In [403]:
df = pd.read_excel('/Users/yaroslav/Desktop/hometask.xlsx')
df = pd.DataFrame(df)
df.head()

Country          Region  Happiness Rank  Happiness Score  \
0  Switzerland  Western Europe               1            7.587   
1      Iceland  Western Europe               2            7.561   
2      Denmark  Western Europe               3            7.527   
3       Norway  Western Europe               4            7.522   
4       Canada   North America               5            7.427   

   Standard Error  Economy (GDP per Capita)   Family  \
0         0.03411                   1.39651  1.34951   
1         0.04884                   1.30232  1.40223   
2         0.03328                   1.32548  1.36058   
3         0.03880                   1.45900  1.33095   
4         0.03553                   1.32629  1.32261   

   Health (Life Expectancy)  Freedom  Trust (Government Corruption)  \
0                   0.94143  0.66557                        0.41978   
1                   0.94784  0.62877                        0.14145   
2                   0.87464  0.64938                        0.48357   
3                   0.88521  0.66973                        0.36503   
4                   0.90563  0.63297                        0.32957   

   Generosity  
0     0.29678  
1     0.43630  
2     0.34139  
3     0.34699  
4     0.45811

## <center>Задание №1</center>
#### <center>Найти медианный ранг (Happines rank) для каждого региона</center>

Воспользуемся функцие groupby, чтобы сгруппировать все наблюдения для каждого региона. В качестве группировки будем использовать медианное значение. 
Как я понимаю, Happines rank - индекс страны при сортировке по Hapinnes score. Найдем медиану по Hapinnes score.

In [404]:
df1 = df.groupby(['Region'], as_index = False).median()
df1.head(3)

Region  Happiness Rank  Happiness Score  \
0   Australia and New Zealand             9.5            7.285   
1  Central and Eastern Europe            77.0            5.286   
2                Eastern Asia            59.5            5.729   

   Standard Error  Economy (GDP per Capita)    Family  \
0        0.037270                  1.291880  1.314450   
1        0.042670                  1.012160  1.106140   
2        0.037245                  1.257675  1.067175   

   Health (Life Expectancy)   Freedom  Trust (Government Corruption)  \
0                  0.919965  0.645310                       0.392795   
1                  0.731280  0.350680                       0.042120   
2                  0.920340  0.466205                       0.079930   

   Generosity  
0    0.455315  
1    0.152750  
2    0.219665

Избавимя от неинтересующих нас данных и получим ответ на первый вопрос задачи.

In [405]:
df1.iloc[:, :2]

Region  Happiness Rank
0        Australia and New Zealand             9.5
1       Central and Eastern Europe            77.0
2                     Eastern Asia            59.5
3      Latin America and Caribbean            41.5
4  Middle East and Northern Africa            79.0
5                    North America            10.0
6                Southeastern Asia            75.0
7                    Southern Asia           117.0
8               Sub-Saharan Africa           132.0
9                   Western Europe            19.0

#### <center>Найти среднюю щедрость (Generosity) по регионам</center>

Аналогично первой части, сгруппируем данные по региону по средним значениям

In [406]:
df2 = df.groupby(['Region'], as_index = False).mean()
df2.head(3)

Region  Happiness Rank  Happiness Score  \
0   Australia and New Zealand             9.5         7.285000   
1  Central and Eastern Europe            79.0         5.332931   
2                Eastern Asia            64.5         5.626167   

   Standard Error  Economy (GDP per Capita)    Family  \
0        0.037270                  1.291880  1.314450   
1        0.045208                  0.942438  1.053042   
2        0.037225                  1.151780  1.099427   

   Health (Life Expectancy)   Freedom  Trust (Government Corruption)  \
0                  0.919965  0.645310                       0.392795   
1                  0.718774  0.358269                       0.086674   
2                  0.877388  0.462490                       0.127695   

   Generosity  
0    0.455315  
1    0.152264  
2    0.225885

Избавимя от неинтересующих нас данных и получим ответ на второй вопрос задачи.

In [407]:
df2.iloc[:, ::9]

Region  Generosity
0        Australia and New Zealand    0.455315
1       Central and Eastern Europe    0.152264
2                     Eastern Asia    0.225885
3      Latin America and Caribbean    0.217788
4  Middle East and Northern Africa    0.190375
5                    North America    0.429580
6                Southeastern Asia    0.419261
7                    Southern Asia    0.341429
8               Sub-Saharan Africa    0.221137
9                   Western Europe    0.302109

## <center>Задание №2</center>
#### <center>Построить график распределения количества стран по регионам</center>

Убедимся, что каждая страна встречается всего один раз. На основе этого мы сможем сделать вывод, что страна принадлежит одному региону, а следовательно количество нахождения региона в таблице равно количеству стран в нем.

In [408]:
len(df.value_counts('Country')) == len(df)

True

Создадим словарь, где будем хранить название региона и количество его упоминаний в таблице.

In [409]:
regions = dict(df.value_counts('Region'))
regions

{'Sub-Saharan Africa': 40,
 'Central and Eastern Europe': 29,
 'Latin America and Caribbean': 22,
 'Western Europe': 21,
 'Middle East and Northern Africa': 20,
 'Southeastern Asia': 9,
 'Southern Asia': 7,
 'Eastern Asia': 6,
 'Australia and New Zealand': 2,
 'North America': 2}

Построим необходимый график. По моему мнению, из-за большой разницы в значениях и малом количестве регионов, самый наглядный график - гистограмма.


In [410]:
fig = px.histogram(x=regions.keys(),y=regions.values())
fig.show()

#### <center>Построить график медианного ранга по регионам</center>

Медианный ранг мы получали в задании 1, возьмем получившиеся данные оттуда. По тем же причинам, построим гистограмму.

In [411]:
to_plot = df1.iloc[:, :2].sort_values('Happiness Rank', ascending = False)
to_plot

Region  Happiness Rank
8               Sub-Saharan Africa           132.0
7                    Southern Asia           117.0
4  Middle East and Northern Africa            79.0
1       Central and Eastern Europe            77.0
6                Southeastern Asia            75.0
2                     Eastern Asia            59.5
3      Latin America and Caribbean            41.5
9                   Western Europe            19.0
5                    North America            10.0
0        Australia and New Zealand             9.5

In [412]:
fig = px.histogram(x=list(to_plot.iloc[:, :1]['Region']), 
                   y=list(to_plot.iloc[:, 1:2]['Happiness Rank']))
fig.show()

#### <center>Построить график средней щедрости по регионам</center>

Выполним все те же действия, что и в предыдущем пункте.

In [413]:
to_plot = df2.iloc[:, ::9].sort_values('Generosity', ascending = False)
to_plot

Region  Generosity
0        Australia and New Zealand    0.455315
5                    North America    0.429580
6                Southeastern Asia    0.419261
7                    Southern Asia    0.341429
9                   Western Europe    0.302109
2                     Eastern Asia    0.225885
8               Sub-Saharan Africa    0.221137
3      Latin America and Caribbean    0.217788
4  Middle East and Northern Africa    0.190375
1       Central and Eastern Europe    0.152264

In [414]:
fig = px.histogram(x=list(to_plot.iloc[:, :1]['Region']), 
                   y=list(to_plot.iloc[:, 1:2]['Generosity']))
fig.show()

#### <center>Построить график, показывающий связь между показателями общественного здоровья и доверия правительству </center>

Кажется, что наиболее подходящим графиком для описания зависимости двух переменных будет прямая.
Построим график прямо из исходных данных.

In [415]:
fig = px.line(x=sorted(list(df['Health (Life Expectancy)'])),
              y=sorted(list(df['Trust (Government Corruption)'])))
fig.show()

## <center>Задание №3</center>
#### <center>К какому типу данных относятся следующие переменные</center>

| Переменная  | Тип данных |
| ------------- | ------------- |
| Country   | Номинальный  |
| Region    | Номинальный  |
| Happiness Rank   | Дискретный  |
| Happiness Score    | Непрерывный  |
| Standard Error   | Дискретный  |
| Economy (GDP per Capita)    | Непрерывный  |
| Family   | Непрерывный  |
| Health (Life Expectancy)     | Дискретный  |
|  Freedom   | Дискретный  |
| Trust (Government Corruption)     | Дискретный  |
| Generosity     | Дискретный  |

#### <center>Посчитайте все разумные меры центральной тенденции и вариации по регионам и странам</center>

Итак, когда мы немного определились с типами данных, но чтобы корректно использовать меры центральной тенденции необходимо также знать на какой шкале располагаются данные. Сделать это относительно непросто, не зная точного происхождения данных. Однако попробуем (укажем их вместе с типом данных).

1. Для данных, расположенных на номинальной шкале можно посчитать только моду.

In [416]:
import statistics

In [417]:
"Наиболее встречающееся значение в наших номинальных данных для 'Country' это {mode_1}, \
а для 'Region' это {mode_2}. При условии, что уникальных значений {count_1} и {count_2} соответсвенно".\
format(mode_1=statistics.mode(df["Country"]), mode_2=statistics.mode(df["Region"]), 
       count_1=df.Country.nunique(), count_2=df.Region.nunique())

"Наиболее встречающееся значение в наших номинальных данных для 'Country' это Switzerland, а для 'Region' это Sub-Saharan Africa. При условии, что уникальных значений 158 и 10 соответсвенно"

2. Для дробно-рациональных можно считать практически все меры центральной тенденции. Выберем наиболее релевантные.

In [418]:
df["Happiness Score"].describe()

count    158.000000
mean       5.375734
std        1.145010
min        2.839000
25%        4.526000
50%        5.232500
75%        6.243750
max        7.587000
Name: Happiness Score, dtype: float64

In [419]:
fig = px.box(df, y="Happiness Score")
fig.show()

In [420]:
df["Trust (Government Corruption)"].describe()

count    158.000000
mean       0.143422
std        0.120034
min        0.000000
25%        0.061675
50%        0.107220
75%        0.180255
max        0.551910
Name: Trust (Government Corruption), dtype: float64

In [421]:
to_plot = df2.iloc[:, ::8].sort_values('Trust (Government Corruption)', ascending = False)
to_plot

Region  Trust (Government Corruption)
0        Australia and New Zealand                       0.392795
5                    North America                       0.244235
9                   Western Europe                       0.231463
4  Middle East and Northern Africa                       0.181702
6                Southeastern Asia                       0.151276
2                     Eastern Asia                       0.127695
8               Sub-Saharan Africa                       0.123878
3      Latin America and Caribbean                       0.117172
7                    Southern Asia                       0.102536
1       Central and Eastern Europe                       0.086674

In [422]:
fig = px.histogram(x=list(to_plot.iloc[:,:1]['Region']),
                   y=list(to_plot.iloc[:,1:2]['Trust (Government Corruption)']))
fig.show()

In [423]:
df["Generosity"].describe()

count    158.000000
mean       0.237296
std        0.126685
min        0.000000
25%        0.150553
50%        0.216130
75%        0.309883
max        0.795880
Name: Generosity, dtype: float64

In [424]:
fig = px.violin(df, y="Generosity", box=True, points="all", hover_data=df.columns)
fig.show()

Можем посмотреть на графики распределения наших данных и как ожидаемо они далеки от нормального распределения (и выбросы, и смещения, и двумадальность). Все это необходимо учитывать при дальнейшей работе с данными для получения корректных результатов.

#### <center>Теперь выберем один регион, например восточную Европу, и построим различные графики для него.</center>

In [425]:
df_gr = df.loc[df.Region == "Western Europe"]

In [426]:
df_g = px.data.tips()
fig = px.scatter(df_gr, x="Happiness Score", y="Economy (GDP per Capita)", trendline="ols")
fig.show()

In [427]:
fig = px.histogram(df, x="Happiness Score")
fig.show()

In [428]:
df_g = px.data.tips()
fig = px.scatter(df_gr, x="Freedom", y="Economy (GDP per Capita)")
fig.show()

#### <center>Вы рандомно взяли одну какую-то страну. Вы ничего не знаете о ней, кроме того, что ее индекс счастья (happiness score) - больше шести. Посчитайте вероятность принадлежности страны к каждому региону.</center>

Выделим из базы данных страны, Happiness Score которых больше 6.

In [429]:
hs = df[df['Happiness Score'] > 6]
hs.head(3)

Country          Region  Happiness Rank  Happiness Score  \
0  Switzerland  Western Europe               1            7.587   
1      Iceland  Western Europe               2            7.561   
2      Denmark  Western Europe               3            7.527   

   Standard Error  Economy (GDP per Capita)   Family  \
0         0.03411                   1.39651  1.34951   
1         0.04884                   1.30232  1.40223   
2         0.03328                   1.32548  1.36058   

   Health (Life Expectancy)  Freedom  Trust (Government Corruption)  \
0                   0.94143  0.66557                        0.41978   
1                   0.94784  0.62877                        0.14145   
2                   0.87464  0.64938                        0.48357   

   Generosity  
0     0.29678  
1     0.43630  
2     0.34139

Самый простой способ приблизительно оценить вероятность того, что любая страна пренадлежит какому-либо региону - посчитать отношение количества вхождения определенного региона в наблюдения, где  Happiness Score больше 6 к общему количеству наблюдений.

In [430]:
hs = dict(hs.value_counts('Region'))
summary = sum(hs.values())
val = np.round(np.array(list(hs.values()))/summary,3)
hs = dict(zip(list(hs.keys()), val))
hs

{'Western Europe': 0.364,
 'Latin America and Caribbean': 0.295,
 'Middle East and Northern Africa': 0.136,
 'Australia and New Zealand': 0.045,
 'Central and Eastern Europe': 0.045,
 'North America': 0.045,
 'Southeastern Asia': 0.045,
 'Eastern Asia': 0.023}

Получили словарь, где напротив региона стоит вероятность того, что страна с Happiness Score больше 6 принадлежит региону.

#### <center>Ваша страна принадлежит к региону "Middle East and Northern Africa". Какова вероятность того, что ее индекс счастья будет принадлежать к первому квартилю? К третьему квартилю?</center>

In [431]:
df['Happiness Score'].describe()

count    158.000000
mean       5.375734
std        1.145010
min        2.839000
25%        4.526000
50%        5.232500
75%        6.243750
max        7.587000
Name: Happiness Score, dtype: float64

Первый квартиль индекса счастья - 4.526000, третий квартиль - 6.243750

In [432]:
east = df[df['Region'] == 'Middle East and Northern Africa'].sort_values('Happiness Score')
first_quantil = len(east[east['Happiness Score'] > 4.526])/len(east)
third_quantil = len(east[east['Happiness Score'] > 6.24375])/len(east)
print(f'''Вероятность того, что страна из Middle East and Northern Africa 
находится в первом квантиле по индексу счастья равна {first_quantil}, в третьем квантиле - {third_quantil}''')

Вероятность того, что страна из Middle East and Northern Africa 
находится в первом квантиле по индексу счастья равна 0.85, в третьем квантиле - 0.3


Сделать какие-либо выводы достаточно сложно из-за того, что мы не знает точного происхождения этих данных. Однако, так как это живые данные, мы можем увидеть их неоднородность и выборы. Но несмотря на это, мы смотри заметить некоторые зависимости в данных, основываясь при этом на интуиции.

P.S. Мы попробовали показать все наши знания в первой части работы. Времени на вторую не осталось😞